# Site settings
title:          DevSighOps
description:    "Making Deployment Boring"
url:            "https://blog.devsighops.com"

# Author
author:
  name:         Tom Butler
  url:          https://blog.devsighops.com/about
  email:        tom@devsighops.com

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5
